name: Release

on: push

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build Catalog
      run: ./hack/generate-catalog.sh
    - name: Tag Release
      id: tag
      uses: mathieudutour/github-tag-action@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.tag.outputs.new_tag }}
        files: |
          catalog.json
          LICENSE
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
