name: Release

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Catalog
        run: ./hack/generate-catalog.sh
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            catalog.json
            LICENSE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
