name: Tag

on:
  push:
    branches:
    - master

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Tag Release
      uses: mathieudutour/github-tag-action@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
